"""empty message

Revision ID: 82d21c9640d4
Revises: ca703e713085
Create Date: 2021-04-30 18:13:08.034662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d21c9640d4'
down_revision = 'ca703e713085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('invoice', sa.String(length=255), nullable=False))
    op.add_column('transactions', sa.Column('type', sa.Enum('Debet', 'Credit'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'invoice')
    # ### end Alembic commands ###
