"""empty message

Revision ID: ca703e713085
Revises: 41f2bf7d6eb2
Create Date: 2021-04-30 18:01:52.126461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca703e713085'
down_revision = '41f2bf7d6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('department', sa.String(length=100), nullable=False))
    op.drop_column('transactions', 'departement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('departement', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('transactions', 'department')
    # ### end Alembic commands ###
